#pragma once
#define MASTER_RIGHT
#define OLED_DISPLAY_128X32
#define SPLIT_OLED_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define OLED_BRIGHTNESS 128
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 3
#define OLED_TIMEOUT 1000